;
; File generated by cc65 v 2.19 - Git b993d88
;
	.fopt		compiler,"cc65 v 2.19 - Git b993d88"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; unsigned char __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     'A'
	sta     $D010
	lda     $01
	sta     $D011
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

