;
; File generated by cc65 v 2.19 - Git b993d88
;
	.fopt		compiler,"cc65 v 2.19 - Git b993d88"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_strlen
	.export		_main

; ---------------------------------------------------------------
; unsigned char __near__ strlen (unsigned char *str)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_strlen: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	jsr     pusha
	jmp     L0004
L0002:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
L0004:	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	cmp     #$00
	jsr     boolne
	jne     L0002
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jmp     L0001
L0001:	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$0D
	jsr     subysp
	ldy     #$0C
L0002:	lda     M0001,y
	sta     (sp),y
	dey
	bpl     L0002
	lda     sp
	ldx     sp+1
	jsr     _strlen
	ldx     #$00
	jsr     pusha
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	ldy     #$0E
	jsr     addysp
	rts

.segment	"RODATA"

M0001:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$21,$00

.endproc

